# Generated by Django 4.1 on 2022-10-22 02:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id_cine', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pelicula_cine', models.CharField(max_length=50)),
                ('nombre_director_cine', models.CharField(max_length=50)),
                ('descripcion_cine', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('username_cine', models.CharField(max_length=50)),
                ('fecha_creacion_cine', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Literatura',
            fields=[
                ('id_literatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_literatura', models.CharField(max_length=50)),
                ('autor_literatura', models.CharField(max_length=50)),
                ('editorial_literatura', models.CharField(max_length=50)),
                ('descripcion_literatura', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('username_literatura', models.CharField(max_length=50)),
                ('fecha_creacion_literatura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id_musica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_artista_musica', models.CharField(max_length=50)),
                ('nombre_disco_musica', models.CharField(max_length=50)),
                ('descripcion_musica', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('username_musica', models.CharField(max_length=50)),
                ('fecha_creacion_musica', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apellido_usuario', models.CharField(max_length=50)),
                ('fecha_nacimiento_usuario', models.DateField()),
                ('email_usuario', models.EmailField(max_length=254, unique=True)),
                ('fecha_creacion_usuario', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenMusica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgmus', models.ImageField(blank=True, null=True, upload_to='musica')),
                ('id_musica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppTPFinal.musica')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenLiteratura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imglit', models.ImageField(blank=True, null=True, upload_to='literatura')),
                ('id_literatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppTPFinal.literatura')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenCine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgcin', models.ImageField(blank=True, null=True, upload_to='cine')),
                ('id_cine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppTPFinal.cine')),
            ],
        ),
    ]
